In [1]:
!nvidia-smi

Mon Apr  8 15:03:47 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.2.1+cu121


## Introduction to tensors

### Tensorler çok boyutlu verileri yani sayısal verileri temsil etmenin bir yoludur

### Creating tensor

PyTorch tensors are created using `torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
# Get tensor back as Python int
scaler.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
# Paratic
TENSOR1 = torch.tensor([[[1,2,3],
                         [9,11,17],
                         [18,19,23]]])
TENSOR1

tensor([[[ 1,  2,  3],
         [ 9, 11, 17],
         [18, 19, 23]]])

In [18]:
TENSOR1.ndim

3

In [19]:
TENSOR1.shape

torch.Size([1, 3, 3])

## Random tensors

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [20]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.3080, 0.7557, 0.1352, 0.0983],
        [0.4648, 0.5433, 0.4396, 0.4531],
        [0.6543, 0.4774, 0.7580, 0.6955]])

torch.rand() fonksiyonunun esnekliği, boyutu istediğimiz şekilde ayarlayabilmemizdir. Örneğin, [224, 224, 3] ([yükseklik, genişlik, renk_kanalları]) ortak görüntü şeklinde rastgele bir tensör istediğinizi varsayalım.

In [21]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224,224,3))# height, width, color_channels(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with torch.zeros()

Again, the size parameter comes into play.

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

We can do the same to create a tensor of all ones except using torch.ones() instead.

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1)
Note: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.

In [24]:
torch.arange(1,4)

tensor([1, 2, 3])

In [25]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.arange(0, 10)

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0,end=10,step=1) # arange is romeved features realese corrert use is arange not range
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note** Tensor datatypes is one of the 3 big errors you''ll run into with PyTorch & deep learning

1.Tensor not right datatype

2.Tensors not right shape

3.Tensors not on the right device


In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], # what datatype is the tensor (e.g.float32 or float16)
                               dtype=None,
                               device=None,# deafult olarak cpu kulanır biz burada google colab üzerinde çalıştığımız için gerek yok 'cpu' or 'cuda'
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor.dtype

torch.float16

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)

dtype - what datatype are the elements within the tensor stored in?

device - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [35]:
# Create a tensor
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.9441, 0.5360, 0.0648, 0.9194],
        [0.4680, 0.7486, 0.1286, 0.3111],
        [0.0866, 0.8648, 0.5314, 0.5605]])

In [36]:
# Find out details about same tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.9441, 0.5360, 0.0648, 0.9194],
        [0.4680, 0.7486, 0.1286, 0.3111],
        [0.0866, 0.8648, 0.5314, 0.5605]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

* Addition

* Substraction

* Multiplication (element-wise)

* Division

* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

Basic operations
Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

They work just as you think they would.


In [37]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [41]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication (is all you need)


ne of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:
(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.

In [43]:
# Element wis multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [44]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [45]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [46]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.1 ms, sys: 0 ns, total: 2.1 ms
Wall time: 2.16 ms


In [47]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 31 µs, sys: 6 µs, total: 37 µs
Wall time: 42 µs


tensor(14)

### One of the most common errors in deep learning (shape errors)

1. The **inner dimensions** must match

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work


2. The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)


##### Burada matrix çarpımlarından oluşacak yeni matrix dış hattın şeklide olacaktır örneğin (2,3) @ (3,2) -> (2,2) matrix olucaktır yada (10,2) @ (2,10) buradada tensor 10 satır 10 sütün olacaktır (10,10) diğer öenmlı nokta ise eğer tensörlerin iç kısımları eşleşmiyorsa matrix çarpımı yapamayız


In [48]:
torch.matmul(torch.rand(10,5),torch.rand(5,8)).shape

torch.Size([10, 8])

In [49]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.8637, 0.1985],
        [1.7055, 0.6535]])

# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

In [50]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

In [51]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues,we can manipulate the shape of one of our tensors using a **transpose**.

Transpoze belirli bir tensörün eksenlerini veya boyutlarını değiştirir


In [52]:
tensor_B,tensor_B.shape

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 torch.Size([3, 2]))

In [53]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([2, 3]))

In [54]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [55]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [56]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Finding the min, max, mean, sum, etc (aggregation)


In [57]:
# Create a tensor
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [58]:
# Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [59]:
# Find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [60]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [61]:
# Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

## Positional min/max


You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

--------------------------------------------------------------------------------

Ayrıca sırasıyla torch.argmax() ve torch.argmin() ile maksimum veya minimumun oluştuğu tensörün indeksini de bulabilirsiniz. Bu, gerçek değerin kendisini değil, yalnızca en yüksek (veya en düşük) değerin olduğu konumu istediğinizde faydalıdır (bunu daha sonraki bir bölümde softmax aktivasyon fonksiyonunu kullanırken göreceğiz).

In [62]:
# Create a tensor
tensor = torch.arange(10,100,10)
print(f"Tensor:{tensor}")
# Returns index of max and min values
print(f"Index where max value occurs:{tensor.argmax()}")
print(f"Index where min value occurs:{tensor.argmin()}")


Tensor:tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs:8
Index where min value occurs:0


## Reshaping, stacking, squeezing and unsqueezing


Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

Method	One-line description

* torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

* Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

* torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

* torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.

*  torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.

* torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.
Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

First, we'll create a tensor.

In [63]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape
# ekstra 1 boyut ekledik tensörümüze yani yeniden şekliendirdik boyut burada satıra denk gelir

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Add an extra dimension
x_reshaped1 = x.reshape(9,1)
x_reshaped1,x_reshaped1.shape
# ekstra 1 boyut ekledik tensörümüze yani yeniden şekliendirdik boyut burada satıra denk gelir 9 satır 1 sütünlu yaptık tensörümüzü ve önemli ayrıntı olarak
# 9X1 = 9 yani tensörümüzün size eşit olmak zorunda örneğin eğer tensörümüzün size 20 olsaydı (9,1) olrak değiştiremezdik

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [66]:
# Change the view
z = x.view(1,9)
z,z.shape
# view aslıdan reshape çok benzerdir

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
# z yi değiştyirmek x'i değiştirir çünkü bir tensörün görünümüz orjinal girişle belleği paylaşır
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [68]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked
# kısacası tensörleri üst üste yığmaya yarar stack fonksiyonu

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [69]:
# torch.squeeze() - removes all single dimendion from a target tensor torch.squeeze() hedef tensördeki tüm tek boyutları kaldırır siler
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [70]:
x_reshaped.shape

torch.Size([1, 9])

In [71]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [72]:
x_reshaped.squeeze().shape # torch.squeeze() - removes all single dimendion

torch.Size([9])

In [73]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [74]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [75]:
# torch.permute -rearranges the dimension of  a target tensor in a specified order  tensörün boyutlarını belirli bir sırayla yeniden düzenler
x_original = torch.rand(size=(224,224,3)) # [height,width,colour_channels]

# Permute the original tensor to rerrange the axis (or dim ) order
x_permuted = x_original.permute(2,0,1) # shift axis 0->1,1->2,2->0

print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}") # [colour_channels,height,width,]

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [76]:
x_original[0,0,0] = 72818
x_original[0,0,0],x_permuted[0,0,0]

(tensor(72818.), tensor(72818.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [77]:
# Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [78]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
# Let's index on the middle bracket (dim=1)
x[0,0]


tensor([1, 2, 3])

In [80]:
# Let's index on the inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [81]:
x[0][2][2]

tensor(9)

In [82]:
# You can also use ":" to seleck "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [83]:
# Get all values 0th and lasr dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [84]:
# Get all values of the dimension but only the index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [85]:
# Get index 0 of 0th 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [86]:
# Index ox x to return 9
x[0,2,2]

tensor(9)

In [87]:
# Index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy


In [88]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor =  torch.from_numpy(array) # numpy arrayini tensöre çeviriyoruz
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
array.dtype

dtype('float64')

In [90]:
tensor.dtype # numpy arrayini tensöre çeviriyor isek default veri tipi floa64

torch.float64

In [91]:
# change the valuen of array,what will this do to 'tensor'
array = array +1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # tensörü numpy çevirdik ve default veri tipi tensörün float32
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [93]:
numpy_tensor.dtype

dtype('float32')

In [94]:
# Change to tensor,what happends to numpy_tensor
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Buradaki anlam aynı hafızayı taşımadıkları için birindeki değişiklik diğerini etkilemez

## Reproducibility(trying to take random out of random )

kısaca sinir ağımızın öğrenme şekli rastgele sayılarla başlamaktadır rastgele sayılar güncelenerek daha iyi temsil sağlanır

**random seed**. kulanarak her seferinde rasgele oluşan tensorlere randomm seed ile belirli tensrü oluşturmamıza imkan sağlar

In [95]:
torch.rand(3,3)

tensor([[0.8884, 0.6332, 0.3901],
        [0.1200, 0.2861, 0.6394],
        [0.4629, 0.5091, 0.5485]])

In [96]:
import torch

# Create two random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A,end="\n\n\n")
print(random_tensor_B,end="\n\n\n")
print(random_tensor_A == random_tensor_B,end="\n\n\n")

tensor([[0.2883, 0.0858, 0.4190, 0.5099],
        [0.7465, 0.2577, 0.5577, 0.8399],
        [0.6723, 0.8236, 0.0998, 0.7787]])


tensor([[0.7381, 0.0182, 0.1424, 0.3212],
        [0.7261, 0.1678, 0.5326, 0.7761],
        [0.5662, 0.4464, 0.9238, 0.3675]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])




In [97]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C,end="\n\n\n")
print(random_tensor_D,end="\n\n\n")
print(random_tensor_C == random_tensor_D,end="\n\n\n")

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])




### Runinng tensors and PyTorch objects on the GPUs (and making faster computations)


In [98]:
### 2.Check for GPU acces with PyTorch
import torch
torch.cuda.is_available()

True

In [99]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [100]:
# Count number of device
torch.cuda.device_count()

1

## 3.Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU because using a GPU result in faster computations

In [102]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [103]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4.Moving tensors back to the CPU


In [104]:
# If tensor is on GPU,can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [105]:
# To fix the GPU tensor NumPy issue,we can first set it to the CPU
tensor_back_on_gpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_gpu

array([1, 2, 3])

### Eğer bir tensör GPU kulanıyorsa device olarak bunu numpy çeviremeyiz  Çevirmek için CPU kulanması gereklidir